### ISSUE TITLE
Adding Azure packages to the mix?

### ISSUE THREAD

**Issue by hongooi73** [r-universe/cloudyr#1]
Hi there,

I have several Azure packages which are part of the Cloudyr org. I only just noticed that Cloudyr is now also part of R-Universe. Would it be possible to mirror those packages here as well, and if so, what needs to be done?

@markedmondson1234

**Comment by MarkEdmondson1234** [comment]
Hi :) I just signed it up as an experiment, I think it's CRAN only packages and perhaps takes the URL from the DESCRIPTION - why that means the Azure ones aren't appearing I don't know but if you open an issue with @jeroen on the r-universe org hopefully he can help.

**Comment by jeroen** [comment]
By default indeed we only include CRAN packages that have your github rep in the URL or BugReports field.

If you want to control yourself which packages appear in your universe, you need to create a repository `universe` under the github account of that universe, with a registry file in this format: https://github.com/ncov-ic/universe and then send me a message, so I will switch over the registry to your personal one.

You can start from this: https://github.com/r-universe-org/cran-to-git/blob/master/cloudyr.json

**Comment by hongooi73** [comment]
Ah, that would explain it. My packages are on CRAN, but the URL field points to the Azure org, not Cloudyr.

There's a bit of a messy history here: Originally they were under my personal account, but then a coworker suggested that I should move them to Cloudyr, which I did. Then our team got a directive that we should consolidate all our Github stuff under the Azure org, so I moved them there, but kept copies on Cloudyr. I'm no longer with MS, but the repos are all still in Azure, and still active. So, eg, https://github.com/Azure/AzureRMR and https://github.com/cloudyr/AzureRMR both exist, and the latter is a mirror of the former.

I'm not sure how to handle this. Will simply adding the Azure repo URLs to the cloudyr.json file suffice? I can't move the Azure repos since I'm not a member of that org.

**Comment by jeroen** [comment]
Yes you can include any R package repository in your personal registry file, it does not matter where it lives. See also this example registry: https://github.com/ncov-ic/universe/blob/main/packages.json

**Comment by hongooi73** [comment]
Oh wait, it's already there lol: https://azure.r-universe.dev/ui#builds

The azuremlsdk package is there as well which is a separate effort, maybe this is the result of scraping CRAN? In any case, looks like I don't have to do anything.

**Comment by jeroen** [comment]
The azuremlsdk package on cran links to this github org: https://cran.r-project.org/web/packages/azuremlsdk/index.html

**Comment by hongooi73** [comment]
Yeah, I know the team involved. Actually, they must have put it on R-Universe along with my stuff and Alex's AzureKusto, since there is a link to the main Azure docs page.

I'll close this, since I guess you don't want the same packages showing up in multiple universes (multiverses?)
